### ISSUE TITLE
CreditCardAsset copies all vendor dir into web/assets

### ISSUE THREAD

**Issue by tdimdimich** [andrewblake1/yii2-credit-card#3]
Don't use:
`public $sourcePath = '@vendor/';`
Create depends

**Comment by havryliv** [comment]
@tdimdimich Thanks for your feedback. You can access `dev-master` version of this library ( where this issue is fixed ).
BR, Yaroslav.

**Comment by tdimdimich** [comment]
oh, I started do fix) Thanks!
